
services:
  db:
    # МЕНЯЕМ alpine на обычный (он более гибкий в правах)
    image: postgres:15 
    container_name: etika-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: etika_db
    ports:
      - "5432:5432"
    volumes:
      # Используем простой путь без привязки к локальной папке для теста
      - db_data_final:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  backend:
    image: php:8.2-apache
    container_name: etika-backend
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    user: root
    command: >
      bash -c "apt-get update && apt-get install -y libpq-dev 
      && docker-php-ext-install pdo pdo_pgsql 
      && a2enmod rewrite 
      && apache2-foreground"

volumes:
  db_data_final: